In [1]:
import numpy as np

In [3]:
arr = np.array(['HTML','CSS','JS','React','Angular','Node.js','jQuery','MongoDB'])
arr

array(['HTML', 'CSS', 'JS', 'React', 'Angular', 'Node.js', 'jQuery',
       'MongoDB'], dtype='<U7')

In [ ]:
print(arr[4])
print(arr[0:])
print(arr[0:5])
print(arr[3:7])
print(arr[:6])
print(arr[2:7:2])

Angular
['HTML' 'CSS' 'JS' 'React' 'Angular' 'Node.js' 'jQuery' 'MongoDB']
['HTML' 'CSS' 'JS' 'React' 'Angular']
['React' 'Angular' 'Node.js' 'jQuery']
['HTML' 'CSS' 'JS' 'React' 'Angular' 'Node.js']
['JS' 'Angular' 'jQuery']


In [16]:
arr = np.array(
    [
        ['HTML','CSS','JS','React','Angular','Node.js','jQuery','MongoDB']
    ])
arr

array([['HTML', 'CSS', 'JS', 'React', 'Angular', 'Node.js', 'jQuery',
        'MongoDB']], dtype='<U7')

In [23]:
print(arr[0,3])
print(arr[0,0:])
print(arr[0,0:5])
print(arr[0,3:])
print(arr[0,1:6])
print(arr[0,0:6])
print(arr[0,0:7:3])

React
['HTML' 'CSS' 'JS' 'React' 'Angular' 'Node.js' 'jQuery' 'MongoDB']
['HTML' 'CSS' 'JS' 'React' 'Angular']
['React' 'Angular' 'Node.js' 'jQuery' 'MongoDB']
['CSS' 'JS' 'React' 'Angular' 'Node.js']
['HTML' 'CSS' 'JS' 'React' 'Angular' 'Node.js']
['HTML' 'React' 'jQuery']


In [49]:
arr = np.array(
    [
        [
            ['HTML','CSS','JS','React'],
            ['Angular','Node.js','jQuery','MongoDB']
        ]
     ])
arr

array([[['HTML', 'CSS', 'JS', 'React'],
        ['Angular', 'Node.js', 'jQuery', 'MongoDB']]], dtype='<U7')

In [54]:
print(arr[0,1,2])
print(arr[0,1,2:4])
print(arr[0,1:])
print(arr[0,1,0:3:2])
print(arr[0,0:2,0:2])

jQuery
['jQuery' 'MongoDB']
[['Angular' 'Node.js' 'jQuery' 'MongoDB']]
['Angular' 'jQuery']
[['HTML' 'CSS']
 ['Angular' 'Node.js']]


In [62]:
np.random.seed(42)
arr = np.arange(100,200,10)
arr

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [65]:
print(arr[5])
print(arr[1:7])
print(arr[6:9])

150
[110 120 130 140 150 160]
[160 170 180]


In [71]:
arr = np.array(
    [
        [
            [100, 110, 120, 130, 140], 
            [150, 160, 170, 180, 190]
        ]
    ])
print(arr)

[[[100 110 120 130 140]
  [150 160 170 180 190]]]


In [67]:
print(arr[0,1:4])

[110 120 130]


In [70]:
print(arr[0,1:4])

[]


In [72]:
print(arr[0,1,2:4])

[170 180]
